<a href="https://colab.research.google.com/github/nehansa2003/Weather-Forecasting-Project/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Load Datasets

In [2]:
colombo=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Colombo.csv')
galle=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Galle.csv')
gampaha=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Gampaha.csv')
kandy=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Kandy.csv')
jaffna=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Jaffna.csv')

In [3]:
print("Colombo :", colombo.shape)
print("Gampaha :", gampaha.shape)
print("Galle   :", galle.shape)
print("Kandy   :", kandy.shape)
print("Jaffna  :", jaffna.shape)

Colombo : (578688, 27)
Gampaha : (894336, 27)
Galle   : (1525632, 27)
Kandy   : (1736064, 27)
Jaffna  : (894336, 27)

Basic Dataset Inspection

In [37]:
datasets = {
    "Colombo": colombo,
    "Gampaha": gampaha,
    "Galle": galle,
    "Kandy": kandy,
    "Jaffna": jaffna
}

for district, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"{district.upper()} DATASET")
    print("=" * 70)

    print("Shape:", df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData types:")
    print(df.dtypes)

    print("\nFirst 5 rows:")
    display(df.head())

======================================================================
COLOMBO DATASET
======================================================================
Shape: (578688, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Colombo,1,6.85991,79.79351,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,9.0,157,SSE,22.0,0.1,0.1,43,0.0,0.0,NaN
1,Colombo,1,6.85991,79.79351,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,5.5,148,SSE,15.8,0.0,0.0,50,0.0,0.0,NaN
2,Colombo,1,6.85991,79.79351,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,4.3,156,SSE,9.7,0.1,0.1,78,0.0,0.0,NaN
3,Colombo,1,6.85991,79.79351,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,3.9,146,SE,8.6,0.1,0.1,92,0.0,0.0,NaN
4,Colombo,1,6.85991,79.79351,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,3.6,96,E,7.2,0.0,0.0,90,0.0,0.0,NaN

======================================================================
GAMPAHA DATASET
======================================================================
Shape: (894336, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,8.1,148,SSE,20.9,0.1,0.1,34,0.0,0.0,NaN
1,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,6.4,133,SE,14.4,0.0,0.0,50,0.0,0.0,NaN
2,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,4.8,138,SE,11.9,0.0,0.0,81,0.0,0.0,NaN
3,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,3.7,119,ESE,9.0,0.0,0.0,92,0.0,0.0,NaN
4,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,4.4,81,E,8.6,0.0,0.0,91,0.0,0.0,NaN

======================================================================
GALLE DATASET
======================================================================
Shape: (1525632, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Galle,1,5.84691,80.221,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,16.4,61,ENE,22.3,0.0,0.0,48,0.0,0.0,NaN
1,Galle,1,5.84691,80.221,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,16.6,56,NE,23.0,0.0,0.0,29,0.0,0.0,NaN
2,Galle,1,5.84691,80.221,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,16.8,55,NE,22.7,0.0,0.0,18,0.0,0.0,NaN
3,Galle,1,5.84691,80.221,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,17.1,60,ENE,23.8,0.0,0.0,22,0.0,0.0,NaN
4,Galle,1,5.84691,80.221,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,17.7,63,ENE,23.8,0.0,0.0,45,0.0,0.0,NaN

======================================================================
KANDY DATASET
======================================================================
Shape: (1736064, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Kandy,1,7.13069,80.53697,808.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,1.8,191,S,3.6,0.0,0.0,20,0.0,0.0,NaN
1,Kandy,1,7.13069,80.53697,808.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,3.3,193,SSW,7.2,0.0,0.0,36,0.0,0.0,NaN
2,Kandy,1,7.13069,80.53697,808.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,2.9,173,S,7.2,0.0,0.0,63,0.0,0.0,NaN
3,Kandy,1,7.13069,80.53697,808.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,1.9,158,SSE,5.8,0.0,0.0,91,0.0,0.0,NaN
4,Kandy,1,7.13069,80.53697,808.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,1.6,153,SSE,5.4,0.0,0.0,96,0.0,0.0,NaN

======================================================================
JAFFNA DATASET
======================================================================
Shape: (894336, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,13.7,67,ENE,22.0,0.0,0.0,97,0.0,0.0,NaN
1,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,13.7,63,ENE,19.1,0.0,0.0,97,0.0,0.0,NaN
2,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,12.4,64,ENE,18.7,0.0,0.0,97,0.0,0.0,NaN
3,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,13.9,65,ENE,18.4,0.1,0.1,95,0.0,0.0,NaN
4,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,12.4,60,ENE,20.2,0.1,0.1,90,0.0,0.0,NaN

Standardize column names

In [38]:
def clean_column_names(df):

    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
        .str.replace("/", "_")
    )

    return df

In [39]:
for district in datasets:

    datasets[district] = clean_column_names(
        datasets[district]
    )

In [40]:
for district, df in datasets.items():

    print(f"\n{district}")
    print(df.columns.tolist())

Colombo
['district', 'pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'rain_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s', 'visibility_m']

Gampaha
['district', 'pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'rain_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s', 'visibility_m']

Galle
['district', 'pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'rain_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s', 'visibility_m']

Kandy
['district', 'pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'rain_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s', 'visibility_m']

Jaffna
['district', 'pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'rain_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s', 'visibility_m']

Resetting the point IDs

In [41]:
district_prefix = {
    "Colombo": "COL",
    "Gampaha": "GAM",
    "Galle": "GAL",
    "Kandy": "KAN",
    "Jaffna": "JAF"
}

for district, df in datasets.items():

    # Preserve original point ID
    df["pointid"] = df["pointid"].astype(int)

    # Create globally unique point ID
    df["global_pointid"] = (
        district_prefix[district]
        + "_"
        + df["pointid"].astype(str).str.zfill(3)
    )

    datasets[district] = df

In [42]:
for district, df in datasets.items():

    print(f"\n{district}")

    display(
        df[
            [
                "district",
                "pointid",
                "global_pointid",
                "latitude",
                "longitude"
            ]
        ].drop_duplicates().head(5)
    )

Colombo

       district  pointid global_pointid  latitude  longitude
0       Colombo        1        COL_001   6.85991   79.79351
52608   Colombo        2        COL_002   6.85991   79.86120
105216  Colombo        3        COL_003   6.85991   79.92889
157824  Colombo        4        COL_004   6.92710   79.72583
210432  Colombo        5        COL_005   6.92710   79.79351

Gampaha

       district  pointid global_pointid  latitude  longitude
0       Gampaha        1        GAM_001   6.97796   79.88538
52608   Gampaha        2        GAM_002   6.97796   79.96179
105216  Gampaha        3        GAM_003   6.97796   80.03821
157824  Gampaha        4        GAM_004   6.97796   80.11462
210432  Gampaha        5        GAM_005   7.05379   79.88538

Galle

       district  pointid global_pointid  latitude  longitude
0         Galle        1        GAL_001   5.84691   80.22100
52608     Galle        2        GAL_002   5.91577   80.08250
105216    Galle        3        GAL_003   5.91577   80.15175
157824    Galle        4        GAL_004   5.91577   80.22100
210432    Galle        5        GAL_005   5.91577   80.29025

Kandy

       district  pointid global_pointid  latitude  longitude
0         Kandy        1        KAN_001   7.13069   80.53697
52608     Kandy        2        KAN_002   7.13069   80.60146
105216    Kandy        3        KAN_003   7.13069   80.66594
157824    Kandy        4        KAN_004   7.13069   80.73043
210432    Kandy        5        KAN_005   7.19465   80.47249

Jaffna

       district  pointid global_pointid  latitude  longitude
0        Jaffna        1        JAF_001   9.56386   79.92646
52608    Jaffna        2        JAF_002   9.56386   79.99249
105216   Jaffna        3        JAF_003   9.56386   80.05851
157824   Jaffna        4        JAF_004   9.56386   80.12454
210432   Jaffna        5        JAF_005   9.62895   79.92646

Combining Five Datasets

In [43]:
weather_df = pd.concat(
    datasets.values(),
    ignore_index=True
)

print("Combined dataset shape:")
print(weather_df.shape)

display(weather_df.head())

Combined dataset shape:
(5629056, 28)

,district,pointid,latitude,longitude,elevation_m,datetime,date,day,month,year,...,winddirection_deg,winddirection_compass,windgust_kmh,rainfall_mm,rain_mm,cloudcover_pct,solarradiation_wm2,sunshineduration_s,visibility_m,global_pointid
0,Colombo,1,6.85991,79.79351,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,157,SSE,22.0,0.1,0.1,43,0.0,0.0,NaN,COL_001
1,Colombo,1,6.85991,79.79351,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,148,SSE,15.8,0.0,0.0,50,0.0,0.0,NaN,COL_001
2,Colombo,1,6.85991,79.79351,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,156,SSE,9.7,0.1,0.1,78,0.0,0.0,NaN,COL_001
3,Colombo,1,6.85991,79.79351,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,146,SE,8.6,0.1,0.1,92,0.0,0.0,NaN,COL_001
4,Colombo,1,6.85991,79.79351,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,96,E,7.2,0.0,0.0,90,0.0,0.0,NaN,COL_001

In [44]:
print(
    weather_df["district"].value_counts()
)

district
Kandy      1736064
Galle      1525632
Gampaha     894336
Jaffna      894336
Colombo     578688
Name: count, dtype: int64

In [45]:
# CHECK GLOBAL POINT ID UNIQUENESS


total_points = weather_df["global_pointid"].nunique()

print("Total unique geographical points:", total_points)

Total unique geographical points: 107

In [46]:
# Check points per district

points_per_district = (
    weather_df
    .groupby("district")["global_pointid"]
    .nunique()
)

print(points_per_district)

district
Colombo    11
Galle      29
Gampaha    17
Jaffna     17
Kandy      33
Name: global_pointid, dtype: int64

Verify Point Location Consistency

In [47]:
point_locations = (
    weather_df
    .groupby("global_pointid")
    .agg(
        district=("district", "nunique"),
        latitude=("latitude", "nunique"),
        longitude=("longitude", "nunique")
    )
    .reset_index()
)

problematic_points = point_locations[
    (point_locations["district"] > 1) |
    (point_locations["latitude"] > 1) |
    (point_locations["longitude"] > 1)
]

print(
    "Points with inconsistent locations:",
    len(problematic_points)
)

display(problematic_points.head())

Points with inconsistent locations: 0

Empty DataFrame
Columns: [global_pointid, district, latitude, longitude]
Index: []

In [48]:
coordinate_check = (
    weather_df
    .groupby("global_pointid")
    .agg(
        latitude_count=("latitude", "nunique"),
        longitude_count=("longitude", "nunique"),
        elevation_count=("elevation_m", "nunique")
    )
    .reset_index()
)

problem_points = coordinate_check[
    (coordinate_check["latitude_count"] > 1) |
    (coordinate_check["longitude_count"] > 1)
]

print(
    "Points with inconsistent coordinates:",
    len(problem_points)
)

Points with inconsistent coordinates: 0

Record Count Per Point

In [49]:
records_per_point = (
    weather_df
    .groupby(
        ["district", "global_pointid"]
    )
    .size()
    .reset_index(
        name="record_count"
    )
)
display(
    records_per_point
    .groupby("district")["record_count"]
    .describe()
)

          count     mean  std      min      25%      50%      75%      max
district
Colombo    11.0  52608.0  0.0  52608.0  52608.0  52608.0  52608.0  52608.0
Galle      29.0  52608.0  0.0  52608.0  52608.0  52608.0  52608.0  52608.0
Gampaha    17.0  52608.0  0.0  52608.0  52608.0  52608.0  52608.0  52608.0
Jaffna     17.0  52608.0  0.0  52608.0  52608.0  52608.0  52608.0  52608.0
Kandy      33.0  52608.0  0.0  52608.0  52608.0  52608.0  52608.0  52608.0

Dateime Column Preparation

In [50]:
weather_df["datetime"] = pd.to_datetime(
    weather_df["datetime"],
    errors="coerce"
)

In [51]:
print(weather_df["datetime"].dtype)

datetime64[ns]

In [52]:
invalid_datetime = weather_df["datetime"].isna().sum()

print("Invalid DateTime records:", invalid_datetime)

Invalid DateTime records: 0

Time Period

In [53]:
print("Minimum datetime:")
print(weather_df["datetime"].min())

print("\nMaximum datetime:")
print(weather_df["datetime"].max())

Minimum datetime:
2020-01-01 00:00:00

Maximum datetime:
2025-12-31 23:00:00

Check duplicate records

In [54]:
print(
    "Total duplicate rows:",
    weather_df.duplicated().sum()
)

Total duplicate rows: 0

Check Missing values

In [55]:
missing = pd.DataFrame({
    "Missing_Count": weather_df.isna().sum(),
    "Missing_Percentage":
        weather_df.isna().mean() * 100
})

missing = missing.sort_values(
    "Missing_Percentage",
    ascending=False
)

display(missing)

                       Missing_Count  Missing_Percentage
visibility_m                 5629056               100.0
district                           0                 0.0
latitude                           0                 0.0
pointid                            0                 0.0
elevation_m                        0                 0.0
datetime                           0                 0.0
date                               0                 0.0
day                                0                 0.0
month                              0                 0.0
year                               0                 0.0
time                               0                 0.0
longitude                          0                 0.0
season                             0                 0.0
temperature_c                      0                 0.0
humidity_pct                       0                 0.0
feelslike_c                        0                 0.0
pressure_hpa                       0                 0.0
windspeed_kmh                      0                 0.0
winddirection_deg                  0                 0.0
dewpoint_c                         0                 0.0
winddirection_compass              0                 0.0
windgust_kmh                       0                 0.0
rain_mm                            0                 0.0
rainfall_mm                        0                 0.0
cloudcover_pct                     0                 0.0
solarradiation_wm2                 0                 0.0
sunshineduration_s                 0                 0.0
global_pointid                     0                 0.0

In [56]:
weather_df.describe()

,pointid,latitude,longitude,elevation_m,datetime,day,month,year,temperature_c,feelslike_c,...,pressure_hpa,windspeed_kmh,winddirection_deg,windgust_kmh,rainfall_mm,rain_mm,cloudcover_pct,solarradiation_wm2,sunshineduration_s,visibility_m
count,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5629056,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,...,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,5.629056e+06,0.0
mean,1.278505e+01,7.263026e+00,8.024512e+01,2.081963e+02,2022-12-31 23:30:00.000011264,1.573266e+01,6.521898e+00,2.022500e+03,2.562631e+01,2.936111e+01,...,1.010153e+03,1.156633e+01,1.853702e+02,2.573790e+01,2.924681e-01,2.924681e-01,7.652097e+01,2.196428e+02,1.435629e+03,NaN
min,1.000000e+00,5.846910e+00,7.972583e+01,0.000000e+00,2020-01-01 00:00:00,1.000000e+00,1.000000e+00,2.020000e+03,9.500000e+00,7.600000e+00,...,9.941000e+02,0.000000e+00,0.000000e+00,4.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
25%,6.000000e+00,6.191230e+00,7.999657e+01,1.000000e+00,2021-07-01 23:45:00,8.000000e+00,4.000000e+00,2.021000e+03,2.370000e+01,2.730000e+01,...,1.008600e+03,5.900000e+00,1.000000e+02,1.510000e+01,0.000000e+00,0.000000e+00,5.600000e+01,0.000000e+00,0.000000e+00,NaN
50%,1.100000e+01,7.130690e+00,8.015175e+01,2.400000e+01,2022-12-31 23:30:00,1.600000e+01,7.000000e+00,2.022500e+03,2.590000e+01,2.980000e+01,...,1.010200e+03,1.020000e+01,2.090000e+02,2.380000e+01,0.000000e+00,0.000000e+00,9.600000e+01,1.000000e+01,0.000000e+00,NaN
75%,1.800000e+01,7.386550e+00,8.053697e+01,4.270000e+02,2024-07-01 23:15:00,2.300000e+01,1.000000e+01,2.024000e+03,2.780000e+01,3.190000e+01,...,1.011700e+03,1.580000e+01,2.560000e+02,3.460000e+01,2.000000e-01,2.000000e-01,1.000000e+02,4.330000e+02,3.600000e+03,NaN
max,3.300000e+01,9.759140e+00,8.079491e+01,1.565000e+03,2025-12-31 23:00:00,3.100000e+01,1.200000e+01,2.025000e+03,3.900000e+01,4.480000e+01,...,1.020500e+03,6.580000e+01,3.600000e+02,1.292000e+02,6.710000e+01,6.710000e+01,1.000000e+02,1.106000e+03,3.600000e+03,NaN
std,8.466568e+00,1.155496e+00,2.962269e-01,3.308751e+02,NaN,8.801371e+00,3.448987e+00,1.708181e+00,3.131120e+00,3.954065e+00,...,2.328382e+00,7.197521e+00,9.111273e+01,1.353845e+01,9.767583e-01,9.767583e-01,3.201292e+01,2.950354e+02,1.715646e+03,NaN

In [57]:
numeric_columns = weather_df.select_dtypes(
    include=np.number
).columns

display(
    weather_df[numeric_columns].describe().T
)

,count,mean,std,min,25%,50%,75%,max
pointid,5629056.0,12.785047,8.466568,1.00000,6.00000,11.00000,18.00000,33.00000
latitude,5629056.0,7.263026,1.155496,5.84691,6.19123,7.13069,7.38655,9.75914
longitude,5629056.0,80.245120,0.296227,79.72583,79.99657,80.15175,80.53697,80.79491
elevation_m,5629056.0,208.196262,330.875121,0.00000,1.00000,24.00000,427.00000,1565.00000
day,5629056.0,15.732664,8.801371,1.00000,8.00000,16.00000,23.00000,31.00000
month,5629056.0,6.521898,3.448987,1.00000,4.00000,7.00000,10.00000,12.00000
year,5629056.0,2022.499544,1.708181,2020.00000,2021.00000,2022.50000,2024.00000,2025.00000
temperature_c,5629056.0,25.626306,3.131120,9.50000,23.70000,25.90000,27.80000,39.00000
feelslike_c,5629056.0,29.361107,3.954065,7.60000,27.30000,29.80000,31.90000,44.80000
humidity_pct,5629056.0,83.498290,11.326494,13.00000,77.00000,85.00000,92.00000,100.00000
dewpoint_c,5629056.0,22.431269,2.370466,-4.60000,21.20000,23.10000,24.10000,28.50000
pressure_hpa,5629056.0,1010.153123,2.328382,994.10000,1008.60000,1010.20000,1011.70000,1020.50000
windspeed_kmh,5629056.0,11.566334,7.197521,0.00000,5.90000,10.20000,15.80000,65.80000
winddirection_deg,5629056.0,185.370169,91.112730,0.00000,100.00000,209.00000,256.00000,360.00000
windgust_kmh,5629056.0,25.737896,13.538447,0.40000,15.10000,23.80000,34.60000,129.20000
rainfall_mm,5629056.0,0.292468,0.976758,0.00000,0.00000,0.00000,0.20000,67.10000
rain_mm,5629056.0,0.292468,0.976758,0.00000,0.00000,0.00000,0.20000,67.10000
cloudcover_pct,5629056.0,76.520965,32.012920,0.00000,56.00000,96.00000,100.00000,100.00000
solarradiation_wm2,5629056.0,219.642834,295.035383,0.00000,0.00000,10.00000,433.00000,1106.00000
sunshineduration_s,5629056.0,1435.629264,1715.645570,0.00000,0.00000,0.00000,3600.00000,3600.00000
visibility_m,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Check hourly continuity

In [58]:
weather_df = weather_df.sort_values(
    ["district", "pointid", "datetime"]
)

weather_df["time_difference"] = (
    weather_df
    .groupby(["district", "pointid"])["datetime"]
    .diff()
)

In [59]:
gaps = weather_df[
    weather_df["time_difference"] > pd.Timedelta(hours=1)
]

print("Number of gaps:", len(gaps))

display(
    gaps[
        [
            "district",
            "pointid",
            "datetime",
            "time_difference"
        ]
    ].head(20)
)

Number of gaps: 0

Empty DataFrame
Columns: [district, pointid, datetime, time_difference]
Index: []

Time-based features

In [60]:
weather_df["hour"] = weather_df["datetime"].dt.hour
weather_df["day_of_week"] = weather_df["datetime"].dt.dayofweek
weather_df["day_of_year"] = weather_df["datetime"].dt.dayofyear

weather_df["is_weekend"] = (
    weather_df["day_of_week"] >= 5
).astype(int)

Cyclical Encoding

In [61]:
weather_df["hour_sin"] = np.sin(
    2 * np.pi * weather_df["hour"] / 24
)

weather_df["hour_cos"] = np.cos(
    2 * np.pi * weather_df["hour"] / 24
)

weather_df["month_sin"] = np.sin(
    2 * np.pi * weather_df["month"] / 12
)

weather_df["month_cos"] = np.cos(
    2 * np.pi * weather_df["month"] / 12
)

In [67]:
cyclical_columns = [
    "hour_sin",
    "hour_cos",
    "month_sin",
    "month_cos"
]

print("Checking cyclical feature columns:\n")

for column in cyclical_columns:

    if column in weather_df.columns:
        print(f"{column} exists")
    else:
        print(f"{column} NOT FOUND")

Checking cyclical feature columns:

hour_sin exists
hour_cos exists
month_sin exists
month_cos exists

In [63]:
# COMPARE RAINFALL COLUMNS
print(
    weather_df[
        ["rainfall_mm", "rain_mm"]
    ].describe()
)

print("\nCorrelation:")
print(
    weather_df[
        ["rainfall_mm", "rain_mm"]
    ].corr()
)

        rainfall_mm       rain_mm
count  5.629056e+06  5.629056e+06
mean   2.924681e-01  2.924681e-01
std    9.767583e-01  9.767583e-01
min    0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00
75%    2.000000e-01  2.000000e-01
max    6.710000e+01  6.710000e+01

Correlation:
             rainfall_mm  rain_mm
rainfall_mm          1.0      1.0
rain_mm              1.0      1.0

In [64]:
difference = (
    weather_df["rainfall_mm"]
    - weather_df["rain_mm"]
).abs()

print(
    "Number of different values:",
    (difference > 0.0001).sum()
)

print(
    "Maximum difference:",
    difference.max()
)

Number of different values: 0
Maximum difference: 0.0

Removing Unecessary Columns

In [65]:
# rain_mm is exactly identical to rainfall_mm
weather_df = weather_df.drop(
    columns=["rain_mm"]
)

# visibility_m contains only missing values
weather_df = weather_df.drop(
    columns=["visibility_m"]
)

print("Removed columns:")
print("- rain_mm       → duplicate of rainfall_mm")
print("- visibility_m  → 100% missing")

print("\nRemaining columns:")
print(weather_df.columns.tolist())

Removed columns:
- rain_mm       → duplicate of rainfall_mm
- visibility_m  → 100% missing

Remaining columns:
['district', 'pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s', 'global_pointid', 'time_difference', 'hour', 'day_of_week', 'day_of_year', 'is_weekend', 'hour_sin', 'hour_cos', 'month_sin', 'month_cos']

Physical Validity Checking

In [68]:
# Humidity
print(
    "Humidity < 0:",
    (weather_df["humidity_pct"] < 0).sum()
)

print(
    "Humidity > 100:",
    (weather_df["humidity_pct"] > 100).sum()
)

# Wind speed
print(
    "Negative wind speed:",
    (weather_df["windspeed_kmh"] < 0).sum()
)

# Rainfall
print(
    "Negative rainfall_mm:",
    (weather_df["rainfall_mm"] < 0).sum()
)

# Cloud cover
print(
    "Cloud cover < 0:",
    (weather_df["cloudcover_pct"] < 0).sum()
)

print(
    "Cloud cover > 100:",
    (weather_df["cloudcover_pct"] > 100).sum()
)

Humidity < 0: 0
Humidity > 100: 0
Negative wind speed: 0
Negative rainfall_mm: 0
Cloud cover < 0: 0
Cloud cover > 100: 0

Organizing Columns

In [69]:
column_order = [
    # Identification
    "district",
    "pointid",
    "global_pointid",

    # Geography
    "latitude",
    "longitude",
    "elevation_m",

    # Time
    "datetime",
    "date",
    "day",
    "month",
    "year",
    "time",
    "season",

    # Weather
    "temperature_c",
    "feelslike_c",
    "humidity_pct",
    "dewpoint_c",
    "pressure_hpa",
    "windspeed_kmh",
    "winddirection_deg",
    "winddirection_compass",
    "windgust_kmh",
    "rainfall_mm",
    "cloudcover_pct",
    "solarradiation_wm2",
    "sunshineduration_s",
    "visibility_m"
]

# Keep only columns that actually exist
column_order = [
    col for col in column_order
    if col in weather_df.columns
]

weather_df = weather_df[column_order].copy()

print("Final columns:")
print(weather_df.columns.tolist())

Final columns:
['district', 'pointid', 'global_pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s']

Save Processed Data

In [72]:
PROCESSED_DIR = "/content/drive/MyDrive/Capstone_Datasets"

WEATHER_FILE = os.path.join(
    PROCESSED_DIR,
    "weather_data_processed_2020_2025.parquet"
)

weather_df.to_parquet(
    WEATHER_FILE,
    index=False,
    engine="pyarrow"
)

print("Processed dataset saved successfully.")

print("\nFile:")
print(WEATHER_FILE)

print("\nDataset shape:")
print(weather_df.shape)

print("\nFile size:")
file_size_mb = os.path.getsize(WEATHER_FILE) / (1024 ** 2)
print(f"{file_size_mb:.2f} MB")

Processed dataset saved successfully.

File:
/content/drive/MyDrive/Capstone_Datasets/weather_data_processed_2020_2025.parquet

Dataset shape:
(5629056, 26)

File size:
75.14 MB

In [73]:

# Save Geographical Point References
point_reference = (
    weather_df[
        [
            "district",
            "pointid",
            "global_pointid",
            "latitude",
            "longitude",
            "elevation_m"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["district", "pointid"]
    )
    .reset_index(drop=True)
)

POINT_FILE = os.path.join(
    PROCESSED_DIR,
    "weather_point_reference.csv"
)

point_reference.to_csv(
    POINT_FILE,
    index=False
)


print("Geographycal Point References Saved.")

print("\nFile:")
print(POINT_FILE)

print("\nNumber of geographical points:")
print(len(point_reference))

display(point_reference.head(10))

Geographycal Point References Saved.

File:
/content/drive/MyDrive/Capstone_Datasets/weather_point_reference.csv

Number of geographical points:
107

  district  pointid global_pointid  latitude  longitude  elevation_m
0  Colombo        1        COL_001   6.85991   79.79351          0.0
1  Colombo        2        COL_002   6.85991   79.86120          5.0
2  Colombo        3        COL_003   6.85991   79.92889         19.0
3  Colombo        4        COL_004   6.92710   79.72583          0.0
4  Colombo        5        COL_005   6.92710   79.79351          0.0
5  Colombo        6        COL_006   6.92710   79.86120          9.0
6  Colombo        7        COL_007   6.92710   79.92889         24.0
7  Colombo        8        COL_008   6.92710   79.99657          8.0
8  Colombo        9        COL_009   6.99429   79.79351          0.0
9  Colombo       10        COL_010   6.99429   79.86120          0.0